version: '3'

services:
  proxy:
    container_name: mechdb-proxy
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.production.conf:/etc/nginx/conf.d/default.conf
      - ./proxy/pma.htpasswd:/etc/nginx/pma.htpasswd
      - ./proxy/html:/usr/share/nginx/html
      - ./uploads:/usr/share/nginx/uploads
    links:
      - web
      - api

  web:
    container_name: mechdb-web
    image: node:10
    working_dir: /src
    command: bash -c 'yarn && yarn start'
    volumes:
      - ./web:/src
    environment:
      - HOST=0.0.0.0
      - API_URL=http://api:3000
    expose:
      - 3000

  api:
    container_name: mechdb-api
    image: node:10
    working_dir: /src
    command: bash -c 'yarn && yarn start'
    volumes:
      - ./api:/src
      - ./uploads:/uploads
    environment:
      - NODE_ENV=production
      - NODE_PORT=3000
    env_file:
      - ./api/api.env
    depends_on:
      - db
    links:
      - db
    expose:
      - 3000

  db:
    container_name: mechdb-db
    image: mongo:4.1-xenial
    restart: always
    expose:
      - 27017

  crawler:
    container_name: mechdb-crawler
    image: maven
    command: mvn clean compile exec:java # builds jar & runs it
    working_dir: /src
    ports:
      - "3060:3000"
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./crawler:/src