version: '3'

services:
  proxy:
    container_name: mechdb-proxy
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./proxy/html:/usr/share/nginx/html
      - ./uploads:/usr/share/nginx/uploads
    links:
      - web
      - api

  web:
    container_name: mechdb-web
    image: node:10
    working_dir: /src
    command: yarn dev
    volumes:
      - ./web:/src
    environment:
      - HOST=0.0.0.0
      - API_URL=http://api:3000
    expose:
      - 3000

  api:
    container_name: mechdb-api
    image: node:10
    working_dir: /src
    command: yarn dev
    volumes:
      - ./api:/src
      - ./uploads:/uploads
    environment:
      - NODE_ENV=development
      - NODE_PORT=3000
    env_file:
      - ./api/api.env
    depends_on:
      - db
    links:
      - db
    expose:
      - 3000

  db:
    container_name: mechdb-db
    image: mongo:4.1-xenial
    restart: always
    expose:
      - 27017

  mongoclient:
    container_name: mechdb-mongoclient
    image: mongoclient/mongoclient
    restart: always
    ports:
      - "3333:3000"
